
# dateset path
dataset_path: /home/LVM_date/zhurz/dataset/SUES-200-512x512
weight_save_path: /home/LVM_date/zhurz/experiments/SUES-200-Benchmark/save_model_weight

#intial parameters
fp16 : 1
classes : 120
image_size: 384

# choose model
model : vit
pretrained: true

# super parameters
batch_size : 8
num_epochs : 60
drop_rate : 0.5
weight_decay : 0.0001
lr : 0.001

# test and evaluate



# if LPN
block : 4

# if SUES-200
height : 200

# runtime
device: cuda
num_workers: 4
pin_memory: true
prefetch_factor: 2
eval_amp: false
eval_chunk_size: 256
lr_milestones: [20, 40]
lr_gamma: 0.1
