# super parameters

batch_size : 16
model : resnet
height : 150
query : drone
classes : 120
num_epochs : 60
drop_rate : 0.2
weight_decay : 0.0005
lr : 0.005
name: dense_200_2022-01-28-15:05:27
dataset_path: /media/data1/Datasets
weight_save_path: /media/data1/save_model_weight
