
# dateset path
dataset_path: /home/sues/media/disk2/Datasets
weight_save_path: /home/sues/media/disk2/save_model_weight

#intial parameters
fp16 : 1
classes : 120
image_size: 384

# choose model
model : vit

# super parameters
batch_size : 8
num_epochs : 60
drop_rate : 0.5
weight_decay : 0.0001
lr : 0.001

# test and evaluate



# if LPN
block : 4

# if SUES-200
height : 200
