# super parameters

batch_size : 8
block : 4
fp16 : 0
model : LPN
height : 150
query : drone
classes : 120
num_epochs : 80
drop_rate : 0.4
weight_decay : 0.0005
lr : 0.006
name: LPN_150_2022-03-24-16:15:57
dataset_path: /media/data1/Datasets
weight_save_path: /media/data1/save_model_weight
#loss_function: contrastive
image_size: 384